name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        file: ./mysite/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t mysite .
        docker tag mysite:latest ${{ secrets.DOCKER_USERNAME }}/mysite:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mysite:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy SSH key
      run: |
        echo "${{ secrets.EC2_KEY_PEM }}" | base64 --decode > /tmp/key.pem
        chmod 600 /tmp/key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i /tmp/key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/wagtail-apps/tree/main/mysite
          docker stop mysite || true
          docker rm mysite || true
          docker run -d --name mysite -p 80:80 ${{ secrets.DOCKER_USERNAME }}/wagtail-apps/tree/main/mysite
        EOF
